checking

diff --git a/.github/workflows/terraform-plan.yml b/.github/workflows/terraform-plan.yml
--- a/.github/workflows/terraform-plan.yml
+++ b/.github/workflows/terraform-plan.yml
@@ -55,7 +55,11 @@ jobs:
           GCP_CREDENTIALS_BASE64: ${{ secrets.GCP_CREDENTIALS_BASE64 }}
           GCP_PROJECT_ID: ${{ secrets.TF_VAR_PROJECT_ID }}
         run: |
-          printf "%s" "$GCP_CREDENTIALS_BASE64" | base64 --decode > "${HOME}/gcp-key.json"
+          echo "${GCP_CREDENTIALS_BASE64}" | tr -d '\r' | base64 --decode > "${HOME}/gcp-key.json"
+          if [ ! -s "${HOME}/gcp-key.json" ]; then
+             echo "Error: GCP key file is empty or invalid"
+            exit 1
+          fi
           gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
           gcloud config set project "$GCP_PROJECT_ID"
 
